# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQZnoELdC4lyVJiAW2-dMx7jrjN2yrxd
"""

# Imput das informações
print("Por favor, informe alguns números e para finalizar, digite '*'")

# Inicialização de variáveis
entrada = ""
sequencia = 0
numerosLidos = []

# leitura dos campos
# 1. Utilize o comando ‘input’ para receber ao menos 2 números de entrada do usuário;
while True:
  sequencia += 1
  print("\nDigite o ", sequencia,"o. número: ")
  entrada = input()
  if entrada == "*":
    break
  else:
    # 2. Converta os valores recebidos pelo usuário para número inteiro (int) ou ponto flutuante (float);
    numerosLidos.append(int(entrada))

if len(numerosLidos) == 1:
  print("\n É preciso que tenha no mínimo dois números. Digite mais um, sff:")
  entrada = input()
  numerosLidos.append(int(entrada))


print("\nForam lidos ", len(numerosLidos), " números, sendo eles: ", numerosLidos)

sequencia = 0
soma = 0
subtracao = 0
multiplicacao = 1
exponenciacao = 1

# 3. Implemente ao menos 4 operações matemáticas em seu código
for sequencia in numerosLidos:
  soma += sequencia
  subtracao -= sequencia
  multiplicacao *= sequencia
  exponenciacao **= sequencia

print("\n A soma de todos os números é: ", soma)
print("\n A subtração do primeiro (", numerosLidos[0], ") e do último (", numerosLidos[-1], ") número é: ", (numerosLidos[0] - numerosLidos[-1]))
print("\n A multiplicação de todos os números é: ", multiplicacao)
print("\n O quadrado do segundo item (", numerosLidos[1] ,") é: ", (numerosLidos[1] ** 2))

# 4. Adicione um laço de repetição ou uma condicional. Por exemplo: você pode permitir que o usuário escolha qual operação realizar ou criar um loop que permita ao usuário realizar várias operações consecutivas;
resposta = ""
print("\n\n Quer saber a média dos números? Se sim, digite 'S'")
resposta = input()
if resposta == 'S' or resposta == 's':
  # 5. Utilize o comando ‘print’ para exibir o resultado da operação matemática.
  print("\n A média dos números é: ", (soma / len(numerosLidos)))